"""
Jarvis Assignment Tool — Phase 4: Document Assembly
====================================================
STRICT ISOLATION: This module does NOT import from any other Jarvis tool module.
Uses only external libraries and standard Python.

Public Functions:
  assemble_assignment(qa_json, filename, format_type)
      - Creates a beautifully formatted Word (.docx) or PowerPoint (.pptx) file
      - Handles both raw QA_JSON and HUMANIZED_QA_JSON
"""

import os
import re
import json
from pathlib import Path

def _parse_qa_json(qa_json: str) -> list[dict]:
    """Extract and parse the JSON array from the input string."""
    raw = qa_json
    if "HUMANIZED_QA_JSON:" in raw:
        raw = raw.split("HUMANIZED_QA_JSON:")[-1].strip()
    elif "QA_JSON:" in raw:
        raw = raw.split("QA_JSON:")[-1].strip()
    elif "QUESTIONS_JSON:" in raw:
        raw = raw.split("QUESTIONS_JSON:")[-1].strip()

    raw = re.sub(r"```(?:json)?", "", raw).strip().rstrip("`").strip()

    try:
        data = json.loads(raw)
        if isinstance(data, list):
            return data
        return []
    except Exception:
        return []

def _create_word_doc(qa_list: list[dict], save_path: str, title: str):
    import docx
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = docx.Document()
    
    # Add Title
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title_para.add_run(title)
    title_run.font.size = Pt(24)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(0x2E, 0x5B, 0x82) # Dark Blue
    
    doc.add_paragraph() # Spacing
    
    for qa in qa_list:
        q_num = qa.get("number", "")
        question = qa.get("question", "").strip()
        answer = qa.get("answer", "").strip()
        
        # Question Heading
        q_heading = f"Q{q_num}. {question}" if q_num else question
        p_q = doc.add_paragraph()
        run_q = p_q.add_run(q_heading)
        run_q.font.bold = True
        run_q.font.size = Pt(12)
        
        # Answer Body - Clean Markdown and split by newlines
        paragraphs = [p.strip() for p in answer.split('\n') if p.strip()]
        
        # Strip UI artifacts from the beginning (like '1 1', '1', '2')
        while paragraphs and re.match(r'^[\d\s]+$', paragraphs[0]):
            paragraphs.pop(0)
            
        for para_text in paragraphs:
            # Remove Markdown headers (##) and bold/italic asterisks (**)
            para_text = re.sub(r'#{1,6}\s*', '', para_text)
            para_text = re.sub(r'\*{1,2}', '', para_text)
            
            # Remove horizontal rules (---)
            para_text = re.sub(r'^-{3,}$', '', para_text.strip())
            
            # Remove isolated LaTeX artifacts if any slipped through
            para_text = re.sub(r'\$\$(.*?)\$\$', r'\1', para_text)
            para_text = re.sub(r'\$(.*?)\$', r'\1', para_text)
            
            # Collapse multiple spaces but preserve the single spaces
            para_text = re.sub(r'[ \t]+', ' ', para_text).strip()
            
            if not para_text:
                continue
                
            p_a = doc.add_paragraph()
            # WD_ALIGN_PARAGRAPH.JUSTIFY often causes huge spaces if the paragraph isn't full, so we use LEFT alignment
            p_a.alignment = WD_ALIGN_PARAGRAPH.LEFT
            run_a = p_a.add_run(para_text)
            run_a.font.size = Pt(11)
        
        # Add a blank line between questions
        doc.add_paragraph()

    doc.save(save_path)

def _create_powerpoint(qa_list: list[dict], save_path: str, title: str):
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.enum.text import PP_ALIGN

    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title_shape = slide.shapes.title
    subtitle = slide.placeholders[1]
    title_shape.text = title
    subtitle.text = "Generated by Jarvis"

    # Content Slides (1 per Q&A)
    # Using 'Title and Content' layout (index 1)
    content_layout = prs.slide_layouts[1]
    
    for qa in qa_list:
        q_num = qa.get("number", "")
        question = qa.get("question", "").strip()
        answer = qa.get("answer", "").strip()
        
        # If answer is too long, we might need multiple slides, but for now we just use a small font
        slide = prs.slides.add_slide(content_layout)
        
        title_shape = slide.shapes.title
        body_shape = slide.placeholders[1]
        
        q_heading = f"Q{q_num}. {question}" if q_num else question
        
        # Truncate title if it's crazy long
        if len(q_heading) > 150:
            title_shape.text = q_heading[:147] + "..."
        else:
            title_shape.text = q_heading
            
        # Customize title font
        for paragraph in title_shape.text_frame.paragraphs:
            paragraph.font.size = Pt(24)
            paragraph.alignment = PP_ALIGN.LEFT

        tf = body_shape.text_frame
        tf.clear() # Clear default bullet
        
        p = tf.paragraphs[0]
        p.text = answer
        p.font.size = Pt(14)
        p.alignment = PP_ALIGN.LEFT
        
        # Disable auto-fit so the font size stays as specified (or let PPT auto-fit, which is default)

    prs.save(save_path)

def assemble_assignment(qa_json: str, filename: str, format_type: str = "word") -> str:
    """
    Assemble the extracted/humanized questions and answers into a formatted document.
    
    Args:
        qa_json: The JSON string output from Phase 2 (generate_answers) or Phase 3 (humanize_answers).
        filename: The desired name of the output file (without extension).
        format_type: "word" (creates .docx) or "ppt" (creates .pptx)
        
    Returns:
        Success message with the saved file path.
    """
    try:
        qa_list = _parse_qa_json(qa_json)
        if not qa_list:
            return "Error: Could not parse any questions/answers from the provided JSON."
            
        desktop_dir = Path.home() / "Desktop"
        base_name = os.path.splitext(filename)[0]
        
        if format_type.lower() in ("ppt", "powerpoint", "presentation"):
            save_path = str(desktop_dir / f"{base_name}.pptx")
            try:
                _create_powerpoint(qa_list, save_path, base_name)
                return f"Successfully created PowerPoint presentation: {save_path}"
            except ImportError:
                return "Error: python-pptx is not installed. Run 'pip install python-pptx' first."
        else:
            save_path = str(desktop_dir / f"{base_name}.docx")
            try:
                _create_word_doc(qa_list, save_path, base_name)
                return f"Successfully created Word document: {save_path}"
            except ImportError:
                return "Error: python-docx is not installed. Run 'pip install python-docx' first."
                
    except Exception as e:
        return f"Document assembly failed: {str(e)}"
